# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82b230e5265481b6f8b5cdffd020ceabaf5957f8ec9ab3e4d8deec38a94a61278abba7f7dc97c7bc86ab419bd56c7727d9ed999417051bff8e345feb01f1bdd8

test:
  secret_key_base: c6af6d425854dc2f06a0b4f9215f19a2a7f346117641b2a3825deb99b9299cab07b3f8828cbb59646fdba8b013e0d6b1adb0ed8d63d729148c71901217ee976c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
